name: Scheduled data update

on: [push]

jobs:
  update:
    name: document
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/pr-fetch@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: Rscript -e 'install.packages(c("fitzRoy", "tidyverse", "here", "fst")'
      - name: style
        run: Rscript -e 'source('~/R_scripts/fitzroy_data/test_script.R', echo=TRUE)'
      - name: commit
        run: |
          git add \*.R
          git commit -m 'style'
      - uses: r-lib/actions/pr-push@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  # A mock job just to ensure we have a successful build status
  finish:
    runs-on: ubuntu-latest
    steps:
      - run: true
