name: fetch footywire data weekly

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "0 20 * * 2"

jobs:
  scrape-and-commit:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - name: Install Dependencies
        run: Rscript -e 'install.packages(c("devtools", "tidyverse", "here", "fst", "cli"))'
      - name: Install fitzRoy
        run: Rscript -e 'devtools::install_github("jimmyday12/fitzRoy")'
      - name: Get data
        run: Rscript -e 'source(here::here("scripts", "footywire_weekly_script.R"), echo = TRUE)'
      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m 'updating weekly_data_process' || echo "No changes to commit"
          git push || echo "No changes to commit"
