name: get new data

on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "0 13 * * *"

jobs:
  scrape-and-commit:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("devtools"))' 
                  -e 'install.packages(c("tidyverse"))' 
                  -e 'install.packages(c("here"))' 
                  -e 'install.packages(c("fst"))' 
                  -e 'devtools::install_github("jimmyday12/fitzRoy")'
      - name: Get data
        run: Rscript -e 'source(here::here("data-raw", "weekly_data_process.R"), echo = TRUE)'
      - name: Commit
        run: |
          git config --global user.name 'James Day'
          git config --global user.email '17557361+jimmyday12@users.noreply.github.com'
          git add .
          git commit -m 'updating weekly_data_process' || echo "No changes to commit"
          git push || echo "No changes to commit"
