on: [push]

name: testing that R script runs

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/pr-fetch@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: Rscript -e 'install.packages(c("fitzRoy", "tidyverse", "here", "fst"))'
      - name: style
        run: Rscript -e 'source(here::here("test_script.R"), echo = TRUE)'
      - name: commit
        run: |
          git add .
          git commit -m 'updating time'
      - uses: r-lib/actions/pr-push@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
